package com.workbuddy.cat

import android.content.Context
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import org.json.JSONObject

/** One animation: a horizontal sheet of square frames. fps == 0 means frames are chosen by code. */
data class Anim(val name: String, val sheet: Bitmap, val frames: Int, val fps: Int, val loop: Boolean) {
    val seconds get() = if (fps > 0) frames.toFloat() / fps else 0f
}

/** The pixel-art sheets shared with the desktop app (assets/sprites, generated by tools/build-sprites.js). */
class Sprites private constructor(ctx: Context) {
    val frame: Int
    val anims: Map<String, Anim>
    val fx: Bitmap
    val fxIndex: Map<String, Int>
    val ball: Bitmap
    val clock: Bitmap
    val clockFrames: Int

    init {
        val am = ctx.assets
        val opts = BitmapFactory.Options().apply { inScaled = false }
        fun load(name: String) = am.open("sprites/$name.png").use { BitmapFactory.decodeStream(it, null, opts)!! }
        val m = JSONObject(am.open("sprites/manifest.json").bufferedReader().readText())
        frame = m.getInt("frameW")
        val a = m.getJSONObject("anims")
        anims = a.keys().asSequence().associateWith { k ->
            val o = a.getJSONObject(k)
            Anim(k, load(k), o.getInt("frames"), o.getInt("fps"), o.optBoolean("loop"))
        }
        fx = load("fx")
        val f = m.getJSONObject("fx")
        fxIndex = f.keys().asSequence().associateWith { f.getInt(it) }
        ball = load("ball")
        clock = load("clock")
        clockFrames = m.optJSONObject("clock")?.optInt("frames", 4) ?: 4
    }

    operator fun get(name: String): Anim = anims[name] ?: anims.getValue("idle")

    companion object {
        @Volatile private var inst: Sprites? = null
        fun get(ctx: Context) = inst ?: synchronized(this) { inst ?: Sprites(ctx.applicationContext).also { inst = it } }
    }
}
